---
# Runtime
verbose: 3
token: lstbknd
api:
  uri: "192.168.99.100:2967"
  tls:
    insecure: true
    ca: "/opt/cert/lastbackend/ca.pem"
    cert: "/opt/cert/lastbackend/client.pem"
    key: "/opt/cert/lastbackend/client-key.pem"

# Etcd database
etcd:
  prefix: lastbackend
  endpoints: ["192.168.99.100:2379"]

# Runtime
runtime:
  interface: "eth1"

dns:
  host: 0.0.0.0
  port: 5353
  default_ip: "127.0.0.1"